# Generated by Django 4.2.6 on 2023-11-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='course',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
