# Generated by Django 4.2.7 on 2023-11-25 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_student_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Account',
        ),
    ]
