# Generated by Django 4.2.7 on 2023-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_account_profile_pic_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='file',
            field=models.FileField(default='This cannot be downloaded', upload_to='documents/'),
        ),
    ]
