# Generated by Django 4.2.7 on 2023-11-28 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_collection_delete_collect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='Collect',
        ),
    ]
